### ISSUE TITLE
Fix dependency Import

### ISSUE THREAD

**Issue by luckcolors** [cj123/allthefirmwares#1]
Import of code.google.com/p/go.crypto/ssh/terminal doesn't work anymore.
Found official repo of the missing dependency https://github.com/golang/crypto.
Hope it helps. :)

**Comment by cj123** [comment]
hi there! thanks for the warning!

I've updated it to golang's official repo, as you'll see in the commit just added.

:smiley_cat:

**Comment by luckcolors** [comment]
Ah thanks. :)
You were quick. XD
