### ISSUE TITLE
How to make only the latest firmware downloads?

### ISSUE THREAD

**Issue by ClassicUA** [cj123/allthefirmwares#3]
Hello.

How to make only the latest firmware downloads?

**Comment by ClassicUA** [comment]
Anybody home?

**Comment by cj123** [comment]
allthefirmwares doesn't have this functionality, you can however download only signed firmwares using `-s`

**Comment by ClassicUA** [comment]
Is it possible to add a function, latest firmware downloads?

**Comment by cj123** [comment]
fixed and released in version 1.7
