### ISSUE TITLE
Can you add an option for downloading a specific firmware for all devices?

### ISSUE THREAD

**Issue by ClassicUA** [cj123/allthefirmwares#4]
Hello.

Can you add an option for downloading a specific firmware for all devices?

Example: you need to download iOS 11.4.1 for all devices on which it came out.

**Comment by cj123** [comment]
fixed in version 1.8 (via 9fc07626b27f9a157ea10334fb076a1cf0f0bc05 and #5)

download the new version and try:

```
./allthefirmwares -filter Version -filterValue 11.4.1
```
