### ISSUE TITLE
IPSW location

### ISSUE THREAD

**Issue by ClassicUA** [cj123/allthefirmwares#6]
Hello.

Is it possible to implement that when downloading a certain firmware for all devices, the firmware is placed in a folder with the name of the device for which the firmware is intended?

Example:
![ipsw store](https://user-images.githubusercontent.com/10756560/44949742-9540ec00-ae40-11e8-87c1-2289eda262bb.png)

**Comment by ClassicUA** [comment]
Anybody home?

**Comment by ClassicUA** [comment]
Anybody home?

**Comment by cj123** [comment]
I got the first “anybody home” message but ignored it. I’m on holiday.

You can separate into identifier folders using -d “./{{.Identifier}}/“ but not using device names at the moment.

**Comment by ClassicUA** [comment]
Sorry.

**Comment by ClassicUA** [comment]
You can give an example of a complete command. “/{{.Identifier}} / " I'm having trouble putting my firmware in folders?

**Comment by ClassicUA** [comment]
Is it possible to add a function?

**Comment by cj123** [comment]
fixed via 03b1dfb in version 1.9. see `allthefirmwares --help` for an example
