### ISSUE TITLE
The same firmware is downloaded again.

### ISSUE THREAD

**Issue by ClassicUA** [cj123/allthefirmwares#7]
The same firmware is downloaded again.
![default](https://user-images.githubusercontent.com/10756560/46626706-cba90f80-cb40-11e8-948e-8dc94fabe9cd.png)

**Comment by ClassicUA** [comment]
!!!

**Comment by cj123** [comment]
dude.

the attached image does not accurately describe your problem, so I don't know what i'm supposed to fix. I assume that '!!!' is made to draw my attention to this?

The iPhone 7 Plus and 8 Plus are devices - not firmwares - that are most definitely not the same.

**Comment by ClassicUA** [comment]
When using {{.Name}}} the same firmware is re-downloaded.
![screenshot_2018-10-24 ios 12 0 1 downloads and information](https://user-images.githubusercontent.com/10756560/47461447-7d0a9f00-d7e9-11e8-9d40-8b3e9ee32862.png)

**Comment by ClassicUA** [comment]
!!!
