### ISSUE TITLE
OTA Deltas

### ISSUE THREAD

**Issue by bvanpeski** [cj123/allthefirmwares#9]
I've been trying to identify OTA iOS slice deltas for a project but it looks like the `https://api.ipsw.me/v4/ota/` API is broken. I think this is due to changes apple made to mesu earlier in the year. I've tried using `type=ota` with the device API call (`https://api.ipsw.me/v4/device/iPod9,1?type=ota`), but the slice delta filenames showing don't match up with the filenames I'm seeing devices actually pull from Apple's servers and I'm trying to understand that discrepancy.

Can IPSW.me still identify iOS slices? Or is that functionality currently broken?

**Comment by cj123** [comment]
Hi! 

This might've just been caused by high server load during the iOS 13 release. Is the problem resolved or do things still look odd?
